#!/command/with-contenv bash
# shellcheck shell=bash
# Start the sip2rtsp service

set -o errexit -o nounset -o pipefail

cd /opt/sip2rtsp

# Replace the bash process with the sip2rtsp process, redirecting stderr to stdout
exec 2>&1
exec python3 -u -m sip2rtsp
