#!/command/with-contenv bash
# shellcheck shell=bash
# Start the dbus service

set -o errexit -o nounset -o pipefail

# Tell S6-Overlay not to restart this service
s6-svc -O .

echo "[INFO] Starting dbus daemon..." >&2

# Replace the bash process with the dbus daemon process, redirecting stderr to stdout
exec 2>&1
exec /usr/bin/dbus-daemon --system --nofork --nopidfile --print-address
