#!/command/with-contenv bash
# shellcheck shell=bash
# Start the pulseaudio service

rm -rf /tmp/pulse-* ~/.pulse/*-runtime

exec 2>&1
exec /usr/local/pulseaudio/bin/pulseaudio --log-level=1 --log-target=stderr --disallow-exit=true --exit-idle-time=180 -v -n -F /etc/pulse/default.pa


