#!/command/with-contenv bash
# shellcheck shell=bash
# Start the baresip service

set -o errexit -o nounset -o pipefail

sleep 1

# Replace the bash process with the baresip process, redirecting stderr to stdout
exec 2>&1
exec baresip -f /etc/baresip -v
