#!/command/with-contenv bash
# shellcheck shell=bash
# Start the onvif-server service

set -o errexit -o nounset -o pipefail

export VERBOSE=false

echo "[INFO] Starting onvif-server..." >&2

# Replace the bash process with the onvif-server process, redirecting stderr to stdout
exec 2>&1
exec node /opt/sip2rtsp/onvif-server/serverMockup.js
